### ISSUE TITLE
Re-creating an app with the same name and domain results in exception

### ISSUE THREAD

**Issue by radu-matei** [deislabs/hippo#292]
I'm testing Hippo by re-creating the same application multiple times and I hit an exception when trying to access the application's endpoint:

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

App:66500629-3193-4239-9918-e3b8dbbec4f0-Channel:6057356a-457f-4287-95da-fa23c9eb5130
App:3a862bb9-1c07-4a05-8c29-b03332f9a696-Channel:79ba0a77-ac0a-4068-9602-2b782eb3eb3e
App:049391ff-4d38-42e6-81ef-ef2c45d7646f-Channel:5d734429-5443-4f6d-9a0e-82da91f02934
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Is there something else that needs to be done when deleting an app? Maybe around domain registration?

**Comment by radu-matei** [comment]
Update: it might be an in-memory dictionary that keeps a reference to the deleted app, restarting the server is a workaround for the issue.
