### ISSUE TITLE
error causing hippo to crash when trying to create an app

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#726]
When I try to create an app, I get this error in the hippo server logs and then hippo crashes. I'm unable to go back to localhost:44467 after that.
```
info: Hippo.Application.Accounts.Commands.CreateTokenCommand[0]
      Hippo Request: CreateTokenCommand   Hippo.Application.Accounts.Commands.CreateTokenCommand
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:44467/api/app to https://localhost:5309/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (internal/errors.js:322:7)
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ServerResponse.end (_http_outgoing.js:815:7)
    at ProxyServer.defaultErrorHandler (/Users/michelle/src/hippo/src/Web/ClientApp/node_modules/http-proxy-middleware/dist/_handlers.js:79:9)
    at ProxyServer.emit (/Users/michelle/src/hippo/src/Web/ClientApp/node_modules/eventemitter3/index.js:210:27)
    at ClientRequest.proxyError (/Users/michelle/src/hippo/src/Web/ClientApp/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:753:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

I am creating an app from the spin deploy command and getting a 500 on the client side:
```
thread 'main' panicked at 'Unable to create Hippo App: ResponseError(ResponseContent { status: 500, content: "{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.6.1\",\"title\":\"An error occurred while processing your request.\",\"status\":500}", entity: Some(UnknownValue(Object({"type": String("https://tools.ietf.org/html/rfc7231#section-6.6.1"), "title": String("An error occurred while processing your request."), "status": Number(500)}))) })', /Users/michelle/src/spin/src/commands/deploy.rs:127:14
```

**Comment by bacongobbler** [comment]
Resolved with https://github.com/deislabs/hippo/pull/730
