### ISSUE TITLE
`spin deploy` receives generic 500 server error

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/hippo#819]
In some cases, a `spin deploy` to a Hippo instance with a bad connection to nomad produces no informational error in the response or in the server logs. Only a generic 500 server error is returned.

**Comment by vdice** [comment]
I've recently encountered this behavior in a few ways:

1. Using a bindle server via its https endpoint but with cert errors.  Many commands compensate for this behavior (eg `hippo login -k`, `spin deploy -k`, but I think the internals of Hippo might need support for ignoring cert errors in some other areas; also maybe `hippo revision add` or `hippo app add`...)
2. Using a bindle server that is fronted with basic auth at the proxy/router level.  In this scenario, all requests require basic auth headers.  Hippo doesn't yet support passing such information where needed.

**Comment by bacongobbler** [comment]
I think we can address the second point. Right now hippo assumes bindle-server is running with the `--unauthenticated` flag. I don't think we should be making that assumption when it comes to production, especially because bindle is a public-facing service.

Here is where Hippo connects to Bindle: https://github.com/deislabs/hippo/blob/b0887251ba9b8f603adb691ffccd60bb266f1a45/src/Infrastructure/Services/BindleService.cs#L17

We should probably add "connection string" support for `BindleClient` so that username/password info can be passed to the HTTP client. That willl have to be done at [bindle-dotnet](https://github.com/deislabs/bindle-dotnet). Once fixed upstream and a new release is out, we can update Hippo.

As for the first point, I think we can address that as well with a feature flag to bindle-dotnet. We will need some way to modify [the `HttpClient` used by bindle-dotnet](https://github.com/deislabs/bindle-dotnet/blob/72497f7ee9caa5f2df30eac881b9b63254b62364/src/Bindle/BindleClient.cs#L39).

**Comment by bacongobbler** [comment]
Here's the stack trace when running in debug mode:

```
fail: Hippo.Application.Revisions.Queries.GetStoragesQuery[0]
      Hippo Request: Unhandled Exception for Request GetStoragesQuery Hippo.Application.Revisions.Queries.GetStoragesQuery
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid, UntrustedRoot
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Deislabs.Bindle.BindleClient.QueryInvoices(String queryString, Nullable`1 offset, Nullable`1 limit, Nullable`1 strict, String semVer, Nullable`1 yanked)
         at Hippo.Infrastructure.Services.BindleService.QueryAvailableStorages(String query, Nullable`1 offset, Nullable`1 limit) in /home/runner/work/hippo/hippo/src/Infrastructure/Services/BindleService.cs:line 86
         at Hippo.Application.Revisions.Queries.ExportStoragesQueryHandler.Handle(GetStoragesQuery request, CancellationToken cancellationToken) in /home/runner/work/hippo/hippo/src/Application/Storage/Queries/GetStoragesQuery.cs:line 31
         at Hippo.Application.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /home/runner/work/hippo/hippo/src/Application/Common/Behaviours/PerformanceBehaviour.cs:line 31
         at Hippo.Application.Common.Behaviours.ValidationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /home/runner/work/hippo/hippo/src/Application/Common/Behaviours/ValidationBehaviour.cs:line 35
         at Hippo.Application.Common.Behaviours.AuthorizationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at Hippo.Application.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /home/runner/work/hippo/hippo/src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs:line 19
```

**Comment by bacongobbler** [comment]
https://github.com/deislabs/bindle-dotnet/pull/19 implements connection string support, including a new "SSL mode" option. Once merged and released, Hippo should be able to take a connection string of the form:

```
{
    "ConnectionStrings":
        "Bindle": "host=https://localhost:8080/v1; sslmode=disable"
}
```

I'll share updates once we get that merged and available.

**Comment by bacongobbler** [comment]
https://github.com/deislabs/hippo/pull/831 was just merged. Going to review #829 then cut a new release with that today.

Once released, adding this to nomad-aws-demo should disable TLS verification:

```
CONNECTIONSTRINGS_BINDLE="Address=http://127.0.0.1:8080/v1;SslMode=disable"
```

**Comment by bacongobbler** [comment]
Following up on this: as of #875, any unhandled exceptions that return a 500 server error will now display the details IFF Hippo is running in "development" mode. This should help us nail down these issues in the future.
