### ISSUE TITLE
update channel api not working as expected

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#849]
I'm wondering if there is a case in which this works. I'm populating all the fields as I would to create a new channel just leaving `active_revision_id` and `certificate_id` blank. 
```
fail: Hippo.Application.Channels.Commands.UpdateChannelCommand[0]
      Hippo Request: Unhandled Exception for Request UpdateChannelCommand Hippo.Application.Channels.Commands.UpdateChannelCommand
      Hippo.Application.Common.Exceptions.ValidationException: One or more validation failures have occurred.
         at Hippo.Application.Common.Behaviours.ValidationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Users/michelle/src/hippo/src/Application/Common/Behaviours/ValidationBehaviour.cs:line 33
         at Hippo.Application.Common.Behaviours.AuthorizationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Users/michelle/src/hippo/src/Application/Common/Behaviours/AuthorizationBehaviour.cs:line 78
         at Hippo.Application.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Users/michelle/src/hippo/src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs:line 19
```

**Comment by gogeterobert** [comment]
I was able to replicate this, when updating a channel and providing the same channel name. Currently at channel up date it checks if the channel name is unique, but it queries all channels from that app, including itself. So this endpoint currently works only when changing the channel name as well
